### PR TITLE
Automatically remove the container when it exits

### PR DESCRIPTION
**Pull request by zvada**
added --rm to ExecStart to automatically remove the container when it exits

### CODE REVIEW

**Comment by djw8605** [comment]
Is this already deployed on gracc-itb?

**Comment by zvada** [comment]
Yeah, it's there, I misplaced it originally now it's in the right place.

**Comment by zvada** [comment]
Any objection to merge this? With `--rm` it does clean up container properly when script finishes. I've also tested to run it manually on the ITB.

**Review by djw8605 — APPROVED** [review]
LGTM

**Pull request merged**
