### PR TITLE
add belle2 to vo_list (GRACC-148)

### PR DESCRIPTION
**Pull request by edquist**
https://ticket.opensciencegrid.org/35935

### CODE REVIEW

**Review by djw8605 — APPROVED** [review]
LGTM

**Review by djw8605 — CHANGES_REQUESTED** [review]
Looking at gracc, the VO name is just "belle"

**Comment by djw8605** [comment]
Hi @edquist, an update on this?

**Comment by edquist** [comment]
Hey @djw8605, thanks for the prod about this, i've updated it to just `belle`.

**Comment by djw8605** [comment]
Are you able to test this and just see what the output looks like?  Is belle non-zero?

**Comment by edquist** [comment]
Yeah i see just one entry:

```
%%
Site: BNL-Belle-II
VO: belle
EarliestEndTime: 1517443200
LatestEndTime: 1519084799
Month: 02
Year: 2018
Infrastructure: Gratia-OSG
GlobalUserName: /C=DE/O=GermanGrid/OU=LMU/CN=Robot - grid client - Thomas Kuhr (Belle II DIRAC service)
Processors: 1
NodeCount: 1
WallDuration: 2585030363
CpuDuration: 2480053822
NormalisedWallDuration: 31020364356
NormalisedCpuDuration: 29760645864
NumberOfJobs: 72657
%%
```

**Review by djw8605 — APPROVED** [review]

**Comment by djw8605** [comment]
Looks perfect.  Merge and cut a release please.

**Pull request merged**
